# Generated by Django 5.1.7 on 2025-05-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Shift Type',
                'verbose_name_plural': 'Shift Types',
            },
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_leave',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_shift',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_swap',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shiftswap',
            name='proposed_shift',
        ),
        migrations.RemoveField(
            model_name='shiftswap',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='shiftswap',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='shiftswap',
            name='requester_shift',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.shifttype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ShiftSwap',
        ),
    ]
